debit_filename: ../data/sample/sample.ofx
savings_filename: ../data/sample/sample.ofx
expense-categories:
  - JunkFood:
    - MCDONALDS
    - KFC
    - Hungry Jacks
    - GUZMAN Y GOMEZ
  - Restaurants:
    - PIG N WHISTLE
  - Rent:
    - RENT
  - Entertainment:
    - CINEMAS
  - Bills:
    - WATER
  - PublicTransport:
    - TRANSLINK
  - Petrol:
    - CALTEX
income-categories:
  - Salary:
    - Pay
